version: '2'
services:
  db:
    image: postgres
  app:
    build: .
    command: /semitki/run_api.sh
    volumes:
      - ./api:/semitki/api
    ports:
      - "8000:8000"
    depends_on:
      - db
  web:
    image: nginx:stable
    ports:
      - "9080:80"
    volumes:
      - ./front/dist:/usr/share/nginx/html

