version: '2'
services:
  db:
    image: postgres
  app:
    build: .
    command: /semitki/ENV/bin/python /semitki/api/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api:/semitki/api
    ports:
      - "8000:8000"
    depends_on:
      - db
  web:
    image: nginx:stable
    ports:
      - "8080:80"
    volumes:
      - ./front/dist:/usr/share/nginx/html

