version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command: /semitki/ENV/bin/python /semitki/api/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/semitki
    ports:
      - "8000:8000"
    depends_on:
      - db

