version: '2'
services:
  db:
    image: postgres
  app:
    build: .
    command: /semitki/run_api.sh
    volumes:
      - ./api:/semitki/api
      - ./storage:/semitki/storage
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - variables.env
  web:
    image: nginx:stable
    ports:
      - "9080:80"
    volumes:
      - ./front/dist:/usr/share/nginx/html
      - ./storage:/usr/share/nginx/html/storage
